stages:
  - lint
  - test
  - publish

.nix-base: &nix-base
  image: nixos/nix
  before_script:
    - echo "extra-experimental-features = nix-command flakes" >> /etc/nix/nix.conf

.dev-only: &dev-only
  except:
    - 1.2x
  only:
    - branches

.prod-only: &prod-only
  only:
    - 1.2x

enet-lint:
  <<: [*nix-base, *dev-only]
  script:
    - nix run .#enet-lint
  stage: lint

enet-test:
  <<: [*nix-base, *dev-only]
  script:
    - nix run .#enet-test
  stage: test

enet-publish:
  <<: [*nix-base, *prod-only]
  id_tokens:
    NPM_TOKEN:
      aud: "npm:registry.npmjs.org"
  script:
    - nix run .#enet-publish
  stage: publish
