// Addresses from enet.h, with hosts as dotted quads
const ENET_HOST_ANY = "0.0.0.0";
const ENET_HOST_BROADCAST = "255.255.255.255";
const ENET_PORT_ANY = 0;

// ENET_SOCKET_NULL from unix.h, and INVALID_SOCKET from win32.h read as a signed integer
const ENET_SOCKET_NULL = -1;

const ENET_VERSION_MAJOR = 1;
const ENET_VERSION_MINOR = 3;
const ENET_VERSION_PATCH = 18;
const ENET_VERSION = 0x01_03_12;

// Host and peer defaults from enet.h
const ENET_HOST_RECEIVE_BUFFER_SIZE = 262_144;
const ENET_HOST_SEND_BUFFER_SIZE = 262_144;
const ENET_HOST_BANDWIDTH_THROTTLE_INTERVAL = 1000;
const ENET_HOST_DEFAULT_MTU = 1392;
const ENET_HOST_DEFAULT_MAXIMUM_PACKET_SIZE = 33_554_432;
const ENET_HOST_DEFAULT_MAXIMUM_WAITING_DATA = 33_554_432;
const ENET_PEER_DEFAULT_ROUND_TRIP_TIME = 500;
const ENET_PEER_DEFAULT_PACKET_THROTTLE = 32;
const ENET_PEER_PACKET_THROTTLE_SCALE = 32;
const ENET_PEER_PACKET_THROTTLE_COUNTER = 7;
const ENET_PEER_PACKET_THROTTLE_ACCELERATION = 2;
const ENET_PEER_PACKET_THROTTLE_DECELERATION = 2;
const ENET_PEER_PACKET_THROTTLE_INTERVAL = 5000;
const ENET_PEER_PACKET_LOSS_SCALE = 65_536;
const ENET_PEER_PACKET_LOSS_INTERVAL = 10_000;
const ENET_PEER_WINDOW_SIZE_SCALE = 65_536;
const ENET_PEER_TIMEOUT_LIMIT = 32;
const ENET_PEER_TIMEOUT_MINIMUM = 5000;
const ENET_PEER_TIMEOUT_MAXIMUM = 30_000;
const ENET_PEER_PING_INTERVAL = 500;
const ENET_PEER_UNSEQUENCED_WINDOWS = 64;
const ENET_PEER_UNSEQUENCED_WINDOW_SIZE = 1024;
const ENET_PEER_FREE_UNSEQUENCED_WINDOWS = 32;
const ENET_PEER_RELIABLE_WINDOWS = 16;
const ENET_PEER_RELIABLE_WINDOW_SIZE = 4096;
const ENET_PEER_FREE_RELIABLE_WINDOWS = 8;

// Protocol limits from protocol.h
const ENET_PROTOCOL_MINIMUM_MTU = 576;
const ENET_PROTOCOL_MAXIMUM_MTU = 4096;
const ENET_PROTOCOL_MAXIMUM_PACKET_COMMANDS = 32;
const ENET_PROTOCOL_MINIMUM_WINDOW_SIZE = 4096;
const ENET_PROTOCOL_MAXIMUM_WINDOW_SIZE = 65_536;
const ENET_PROTOCOL_MINIMUM_CHANNEL_COUNT = 1;
const ENET_PROTOCOL_MAXIMUM_CHANNEL_COUNT = 255;
const ENET_PROTOCOL_MAXIMUM_PEER_ID = 4095;
const ENET_PROTOCOL_MAXIMUM_FRAGMENT_COUNT = 1_048_576;

// Wrapping time comparisons from time.h
const ENET_TIME_OVERFLOW = 86_400_000;

export {
  ENET_HOST_ANY,
  ENET_HOST_BANDWIDTH_THROTTLE_INTERVAL,
  ENET_HOST_BROADCAST,
  ENET_HOST_DEFAULT_MAXIMUM_PACKET_SIZE,
  ENET_HOST_DEFAULT_MAXIMUM_WAITING_DATA,
  ENET_HOST_DEFAULT_MTU,
  ENET_HOST_RECEIVE_BUFFER_SIZE,
  ENET_HOST_SEND_BUFFER_SIZE,
  ENET_PEER_DEFAULT_PACKET_THROTTLE,
  ENET_PEER_DEFAULT_ROUND_TRIP_TIME,
  ENET_PEER_FREE_RELIABLE_WINDOWS,
  ENET_PEER_FREE_UNSEQUENCED_WINDOWS,
  ENET_PEER_PACKET_LOSS_INTERVAL,
  ENET_PEER_PACKET_LOSS_SCALE,
  ENET_PEER_PACKET_THROTTLE_ACCELERATION,
  ENET_PEER_PACKET_THROTTLE_COUNTER,
  ENET_PEER_PACKET_THROTTLE_DECELERATION,
  ENET_PEER_PACKET_THROTTLE_INTERVAL,
  ENET_PEER_PACKET_THROTTLE_SCALE,
  ENET_PEER_PING_INTERVAL,
  ENET_PEER_RELIABLE_WINDOWS,
  ENET_PEER_RELIABLE_WINDOW_SIZE,
  ENET_PEER_TIMEOUT_LIMIT,
  ENET_PEER_TIMEOUT_MAXIMUM,
  ENET_PEER_TIMEOUT_MINIMUM,
  ENET_PEER_UNSEQUENCED_WINDOWS,
  ENET_PEER_UNSEQUENCED_WINDOW_SIZE,
  ENET_PEER_WINDOW_SIZE_SCALE,
  ENET_PORT_ANY,
  ENET_PROTOCOL_MAXIMUM_CHANNEL_COUNT,
  ENET_PROTOCOL_MAXIMUM_FRAGMENT_COUNT,
  ENET_PROTOCOL_MAXIMUM_MTU,
  ENET_PROTOCOL_MAXIMUM_PACKET_COMMANDS,
  ENET_PROTOCOL_MAXIMUM_PEER_ID,
  ENET_PROTOCOL_MAXIMUM_WINDOW_SIZE,
  ENET_PROTOCOL_MINIMUM_CHANNEL_COUNT,
  ENET_PROTOCOL_MINIMUM_MTU,
  ENET_PROTOCOL_MINIMUM_WINDOW_SIZE,
  ENET_SOCKET_NULL,
  ENET_TIME_OVERFLOW,
  ENET_VERSION,
  ENET_VERSION_MAJOR,
  ENET_VERSION_MINOR,
  ENET_VERSION_PATCH,
};
